added linkresolver
teamnovu/utils pull request #3
Opened 2021-12-06 20:31 UTC by theLeroy

Mooin

Hab hier ein Modul, dass ich gefunden habe bisle angepasst und in das novu Utils integriert. 

Das modul löst das Problem dass, man von statamic Raw html mit integrierten <a> tags bekommt. Die A tags können aber auch auf einen entry zeigen wofür eigentlich einen Nuxtlink benötigt wird. Das modul entfernt die html eigenen Event Listeners und fügt seine eigenen hinzu. 

Würdmich über Feedback freuen.  

Mit freundlichen Grüßen Janis ;)

2021-12-06 20:34 UTC, theLeroy commented
@Buffalom Ich habe jetzt noch nicht das mit yarn release usw. gemacht. Kann/darf/soll ich das selbst machen wen ihr den Code ok findet?

2021-12-07 08:24 UTC, Buffalom requested changes
Hesch gägäüber däm angerä Package no öppis müessä änderä, oder warum heschs ids utils ta statt eifach ds angerä zinstallierä?

2021-12-07 08:24 UTC, Buffalom commented on vue/linkResolver/index.js
> +      if (href && href[0] === '/') {
Bisch sicher, dass ds längt? Isch d URL vom CMS nid prefixed mit dr AppUrl?

2021-12-07 08:24 UTC, Buffalom commented on vue/linkResolver/index.js
> +    el.$destroy = () => el.removeEventListener('click', removeListeners(links))
Ds gseht chli komisch us dünkts mi. Söttsch da nid eifach nur `removeListeners(links)` ufrüefä?

2021-12-07 08:24 UTC, Buffalom commented on vue/linkResolver/index.js
> +      Vue.nextTick(() => addListeners(links))
Hie drzwüschä muesch doch no d links update oder nid? Süsch duesch ja d Listeners eifach uf di autä Links.

2021-12-07 08:24 UTC, Buffalom commented on vue/linkResolver/index.js
> +  componentUpdated: el => el.$componentUpdated(),
Chasch `$componentUpdated` nid eifach diräkt hie druf tue statt hie ä Function druf ztuä wo när di angeri called? Same thing mitem destroy.

2021-12-07 12:40 UTC, closed without merging